
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: nest_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/crud_db
    volumes:
      - ./backend:/app:cached
    depends_on:
      - db
    command: npm run start:dev


volumes:
  db_data:
  jenkins_home:
