
services:

  backend:
    build: ./backend
    container_name: nest_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:cached
    command: sh -c "npx prisma generate && npx prisma db push && npm run start:dev"

